### ISSUE TITLE
blockquote markdown?

### ISSUE THREAD

**Issue by prezaei** [allejo/jekyll-docs-theme#12]
Hey, thanks for the great theme. 

It does seem to me that there is no styling being applied to "blockquote".

https://commonmark.org/help/tutorial/05-blockquotes.html 

Even though, the correct HTML element is emitted.

**Comment by allejo** [comment]
Oops! Looks like I hadn't been using any blockquotes in my development so I hadn't noticed :sweat_smile:

Thanks for pointing this out, fixed in latest master :+1:

**Comment by prezaei** [comment]
Thanks, man. Don't you need to bump the version? I am using this as a remote theme and don't seem to be able to get the latest.

**Comment by allejo** [comment]
I'll bump the version this weekend. I want to first add a test page with all markdown elements as an example to make double check there aren't other elements I've gotten to style.

In the meanwhile, you can use `@master` or omit the `@...` entirely for the theme version and it should pull the latest version of the theme which includes the blockquote fix.

**Comment by allejo** [comment]
I've published `v1.0.0` 😄
