### ISSUE TITLE
Space between h2 blocks/subsections

### ISSUE THREAD

**Issue by royfrancis** [allejo/jekyll-docs-theme#14]
I can see that h1 blocks are defined into sections which allow for adjusting spacing between them. Is it possible to somehow adjust spacing between h2 blocks or "sub-sections"? Not really sure if this is a theme issue or jekyll or kramdown.

**Comment by allejo** [comment]
I'm not quite sure I follow, do you have a screenshot regarding what you mean?

**Comment by royfrancis** [comment]
![Screenshot from 2022-01-19 20-24-47](https://user-images.githubusercontent.com/5083500/150201400-35263f79-9745-4c02-81ca-522a1538ce14.png)

I was referring to the `section` with class `scope-markdown`. Actually now I just realized that nearly all the [page contents](https://github.com/allejo/jekyll-docs-theme/blob/master/_layouts/page.html#L28) go into it and sections are unrelated to h1 tags. I initially thought that a block of content from an h1 tag to the next h1 tag was defined as a section. And I was hoping to do something similar with h2 tags.

I am looking for a way to controlling spacing between h2 "sections".

**Comment by allejo** [comment]
Hi! Sorry, this issue slipped through the cracks. So the `<section>` is part of the theme layout, however, anything inside of that section is all generated by Kramdown or your markdown engine of choice.

That being said, if you'd like to increase the space between `h2`s visually, you can totally do this via CSS like so,

```css
.scope-markdown h2 {
  margin-top: 1rem;
}
```

The purpose of the `.scope-markdown` class is for people to hook into it and add their own styles :smile:
