### ISSUE TITLE
_site different from dev server

### ISSUE THREAD

**Issue by chemalopezp** [allejo/jekyll-docs-theme#2]
Hi Allejo,

Not sure this is an issue or just something missing on my side, do you know why _site folder HTML files are different from those generated by the jekyll dev server?
<img width="832" alt="screen shot 2017-08-15 at 13 32 18" src="https://user-images.githubusercontent.com/15825354/29335086-5c0f106a-81be-11e7-9c2b-c35719d84132.png">
<img width="632" alt="screen shot 2017-08-15 at 13 32 13" src="https://user-images.githubusercontent.com/15825354/29335085-5c0e7e84-81be-11e7-86fa-78c1a1e85246.png">

Thank you for your help and for the theme, I'm using it for my docs ;)

**Comment by allejo** [comment]
I think this is the CSS file not loading properly because the URL's off. Are you opening the HTML files individually or through a web server?

**Comment by chemalopezp** [comment]
Thanks allejo, this looks quite accurate.

I'm still figuring out the best way to publish, at the beginning I was considering GiHub Pages but I have just realized that it would be so easy to install the custom theme.

Another option would be to just connect it to the express server that I am already using for other routes (/docs/_site/index.hmtl) but this is generating the errors above because the relative URL issue. What would you recommend?

**Comment by chemalopezp** [comment]
One more update allejo, I have partially solved the issue adding 
```
baseurl: "/docs"
```
Since I'm publishing it using express into /docs
```
app.use('/docs', express.static('docs/_site/'));
```
Although I'm still wondering what would be the best way to publish it ;)
Thanks!

**Comment by allejo** [comment]
Publishing to [Github Pages](https://pages.github.com/) or [Netlify](https://www.netlify.com/) are the more common approaches.

When hosting a Jekyll site you're going to want to publish everything inside the _site/ folder. So your Document Root for the web server should be the _site/ folder itself. If you're publishing the Jekyll site into a subfolder of your Document Root, then that's where `baseurl` comes in. It'd be `/docs` as seen in the following example:

```
public_html/
|- docs/
   |- index.html
|- index.html
```

**Comment by chemalopezp** [comment]
Thanks allejo, that was definitely very useful.
As you can see I'm not really familiar with jekyll, but if you need help to test new theme features let me know!
