### ISSUE TITLE
[Question] Sidebar

### ISSUE THREAD

**Issue by MehdiAria** [allejo/jekyll-docs-theme#3]
I'm using this theme and wondering about how to put child parents under the sidebar navigation.

**Comment by allejo** [comment]
What do you mean by "child parents?" At the moment, only the table of contents is placed in the sidebar, but you could [override](https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/#customizing-your-jekyll-themes-html-layout) [`_layouts/page.html`](https://github.com/allejo/jekyll-docs-theme/blob/master/_layouts/page.html) or make your own layout based on this layout as well.
