### ISSUE TITLE
Tables do not look like tables

### ISSUE THREAD

**Issue by xarkes** [allejo/jekyll-docs-theme#9]
Since bootstrap is used, why not adding the `table` class to the generated tables?
Or maybe am I missing something?
I'm creating the table like this:
```
| Column 1 | Column 2 |
| -------- | -------- |
| Row 1    | Row 2    |
```

**Comment by xarkes** [comment]
Okay, I'll use that trick for now, thanks.

**Comment by allejo** [comment]
I'm going to close this as the latest changes in the `develop` branch fixes this.
